import json, hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[1]; D='2026-10-05'
def read(p):return json.loads((R/p).read_text())
def write(p,x):(R/p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
tr=dict(id='tr-report-2026-10',publisher='Teknologirådet',title='Datasentre i Norge – vurderinger av samfunnsnytte',url='https://teknologiradet.no/publication/datasentre-i-norge-vurderinger-av-samfunnsnytte/',publishedAt=D,documentDate='2026-10',retrievedAt=D,accessedAt=D,type='published_analysis_report',access='local_pdf_fulltext',localFile='report/Datasentre-i-Norge.pdf',sha256=hashlib.sha256((R/'report/Datasentre-i-Norge.pdf').read_bytes()).hexdigest(),version='ISBN 978-82-8400-045-9; ingen eksplisitt revisjonskode',locator='Trykte sidetall; PDF-side = trykt side minus 2 fra trykt side 4',dateNote='Publiseringsside datert 05.10.2026; PDF oppgir oktober 2026. Analyse, ikke kommende anbefalingsrapport.')
x=read('research/pastander.json'); x['schemaVersion']=2; x['updatedAt']=D; x['scope']='Rapportbasert oppdatering med intern konsistenskontroll. Underliggende nasjonale raddata er ikke reprodusert.'; x['historyFile']='research/history/2026-10-01/pastander.json';x['sources']=[s for s in x['sources'] if s['id']!=tr['id']]+[tr]
by={c['id']:c for c in x['claims']}
c=by['report-publication'];c.update(claim='Analyserapporten Datasentre i Norge – vurderinger av samfunnsnytte foreligger i fulltekst.',attribution='Teknologirådets rapport og publiseringsside',assessment='confirmed_publication',reason='Lokal PDF lest; offisiell publiseringsside datert 05.10.2026. Anbefalingsrapport varsles separat.',sourceIds=[tr['id']],publishAsFact=True,gaps=['Kommende anbefalingsrapport er en separat publikasjon.'],uncertainty={'type':'qualitative','level':'high_for_source_match','reason':'Dokumentet foreligger; dette godkjenner ikke alle rapportens beregninger.'})
for cid in ['foreign-ownership','reserved-grid-share','value-per-energy','capacity-is-consumption','nature-impact']:
 c=by[cid];c['sourceIds']=list(dict.fromkeys(c['sourceIds']+[tr['id']]));c['reviewedAt']=D
by['foreign-ownership']['reportObservation']={'value':90,'unit':'percent','precision':'approximately','referenceDate':'2026-05-21','locator':'s. 65 figur 13; s. 68–69 metode','weighting':'MW fordelt etter aksjeandel og eierland','verification':'confirmed_in_report_not_independently_reproduced'}
by['foreign-ownership'].update(assessment='report_method_known_not_reproduced',reason='Omtalens 90,6 % bevares. Rapporten oppgir omtrent 90 %, med eierandelvektet kapasitet. Raddata mangler for selvstendig reproduksjon.',gaps=['192-raders Datasenteroversikt','Gjennomgående referansedato og kapasitetsnevner','Eierkjeder og landtilordning per eierledd','Avstemming av 90,6 % i omtale mot avrundet 90 % i rapport'],uncertainty={'type':'qualitative','level':'high_for_attribution_only','reason':'Metoden og avrundet rapportpåstand er lest; aggregatet er ikke reprodusert.'})
by['reserved-grid-share'].update(assessment='older_claim_with_new_report_observation',reason='47 % er eldre omtale. Rapporten sier over 50 % i september 2026. Oppgitte 4220/8179 gir 51,6 %, men underliggende rader, lik avgrensning og dobbelttelling er ikke kontrollert.',reportObservation={'numeratorMW':4220,'denominatorMW':8179,'derivedPercent':round(4220/8179*100,2),'referencePeriod':'2026-09','locator':'s. 15 og 18','calculation':'4220 / 8179 * 100','verification':'arithmetic_only'},gaps=['Datert Statnett-eksport og avstemming av nevner','Tilfeller på særlige vilkår og eventuell dobbelttelling','Forskjell mot tidligere 47 %'])
by['value-per-energy']['reportCrossCheck']={'locator':'s. 38–40','result':'Rapporten støtter den eksisterende tids- og populasjonsavgrensningen. Ingen generell dom om fremtidige KI-anlegg.'}
by['capacity-is-consumption'].update(reason='MW beskriver kapasitet, ikke årsenergi. Rapporten bruker både ca. 955 MW kartlagt kapasitet og 964,4 MW med NVE-basert historisk serie. Avvik og scenarioforutsetninger må bevares.',gaps=['Avstemming av kartlagt baseline 126,05 MW og NVE-baseline 135 MW','Underliggende raddata','Målt energi for samme populasjon'])
by['nature-impact'].update(reason='Naturkapitlet s. 51–55 er lest. Det omtaler generell nedbygging, følgeinngrep og vann, men gir ikke prosjektbasert nasjonalt naturtapsregnskap for datasentre.',attribution='Kontroll av publisert rapports naturkapittel',sourceLocators={tr['id']:'s. 51–55'},assessment='knowledge_gap_after_report_review')
new=[dict(id='report-capacity-baseline',topic='kraft',claim='Rapporten bruker forskjellige historiske basiser for tilknyttet kapasitet.',assessment='internal_basis_discrepancy',reason='126,05 + 799,4 + 30 = 955,45 MW; 135 + 799,4 + 30 = 964,4 MW. Rapporten forklarer forskjellen i fotnote 31. Ikke et statistisk intervall.',locator='s. 13–14, 32 og 69'),dict(id='report-2026-sum',topic='kraft',claim='Oppgitt total 1894 MW samsvarer ikke med brødtekstens 955 + 930 MW.',assessment='internal_arithmetic_discrepancy',reason='955 + 930 = 1885. 964,4 + 930 = 1894,4, som tyder på bruk av annen baseline; må avklares.',locator='s. 14'),dict(id='report-owner-unit',topic='eierskap',claim='Rapportens tekst og figur blander operatører og enkeltanlegg.',assessment='internal_scope_discrepancy',reason='Figur 14 gjelder operatører, mens teksten sier fire anlegg. Bitdeer/Straitdeer oppgis med 26 % i tekst og 25 % i figuren.',locator='s. 65 figur 14'),dict(id='report-full-realisation-scenario',topic='kraft',claim='87,8 TWh er et scenario med full realisering og 70 % kapasitetsfaktor.',assessment='scenario_not_forecast',reason='14320,4 MW * 8760 timer * 0,70 / 1000000 = 87,8126928 TWh. Reproduksjon av regnestykket bekrefter ikke input, realisering eller sannsynlighet.',locator='s. 13 og 15–17')]
for c in new:
 c.update(sourceIds=[tr['id']],attribution='Teknologirådets rapport; egen intern kontroll',reviewedAt=D,claimType='interpretation_check',publishAsFact=False,uncertainty={'type':'qualitative','level':'high_for_document_check','reason':'Dokument-/aritmetikkontroll, ingen selvstendig nasjonal datavalidering.'})
x['claims']=[c for c in x['claims'] if c['id'] not in {n['id'] for n in new}]+new
write('research/pastander.json',x)
p=read('research/prosjekter.json');p['meta'].update(version='0.3.0',updatedAt=D,historyFile='research/history/2026-10-01/prosjekter.json',enrichmentPolicy='Nye rapportpåstander er attribuerte; tidligere verdier og datoer beholdes. Manglende egenskaper er null, ikke fravær av påvirkning.')
p['sources']=[s for s in p['sources'] if s['id']!=tr['id']]+[tr]
for a in p['projects']:
 a['researchDimensions']={'operatingModel':None,'workloads':None,'ownershipLayers':{'landAndBuilding':None,'operator':None,'hardware':None,'digitalServiceProvider':None},'energyServices':{'deliveredHeatMWh':None,'measurementPeriod':None,'recipient':None,'verifiedFlexibility':None},'status':'unknown_unless_supported_by_claim','evidencePolicy':'Utfylles fra claim med kilde, periode og kontrollstatus. Null betyr ikke undersøkt eller ikke dokumentert.'}
 a['claims']=[c for c in a['claims'] if c.get('addedIn')!='2026-10-05-report-review']
 def add(field,value,unit,kind,period,loc,reason):
  a['claims'].append(dict(field=field,value=value,unit=unit,kind=kind,period=period,sourceIds=[tr['id']],sourceLocators={tr['id']:loc},confidence='høy for attribusjon; ikke uavhengig verifisert',reason=reason,uncertaintyType='documented_confidence_level',confidenceInterval=None,publishAsFact=False,verificationStatus='confirmed_in_report_not_independently_verified',addedIn='2026-10-05-report-review'))
 if a['id']=='gromstul':
  add('power',126,'MW','report_attributed_connected_capacity','rapportens kartlegging 2026','s. 32 og 69','Rapporten bruker også begrepet installert effekt. WS Computing 120 MW + WSC 6 MW er koblet via samme transformatorstasjon. Ikke målt last eller bekreftet drift; behold 240 MW som annen kilde/fase.')
  add('operating_model','hyperscale',None,'report_classification','2026-10','s. 31–32','Rapportens modellklassifisering, ikke selvstendig kontroll av kontrakter.')
  add('ownership','WS Computing AS → Raiden Unlimited Company → Alphabet',None,'report_attributed_company_chain','rapportens kartlegging 2026','s. 69','Rapporten oppgir 100 % for første eierledd. Full datert registerkjede må kontrolleres.')
 if a['id']=='n01':add('power',625,'MW','report_attributed_reserved_capacity','frem mot 2035','s. 66','Reservert kapasitet; ikke det samme som markedsført potensial 1000 MW eller eldre mål 400 MW. Statnett-rader mangler.')
 if a['id']=='rjukan':add('energy_services','Hima Seafood som mottaker av overskuddsvarme',None,'report_attributed_heat_reuse_plan','rapport oktober 2026','s. 47, fotnote 195','Rapporten sier skal utnytte. Målt leveranse og oppstart er ikke kontrollert; erstatter ikke tidligere klargjort-status med dokumentert effekt.')
 if a['id']=='hamar':
  add('value_creation',6100000000,'NOK','report_cross_check_construction_phase','første tre bygg','s. 42 fotnote 158','Støtter faseavgrensning mot eldre 9 mrd for fem bygg. Eksisterende Menon-kilde presiserer 5,7 mrd modellert fra investeringer og 0,4 mrd forventet; behold dette forbeholdet.')
write('research/prosjekter.json',p)
write('research/raw/teknologiradet-2026-10-05/report-manifest.json',{'reviewedAt':D,'source':tr,'scope':'Rapport lest og sentrale figurer/fotnoter visuelt kontrollert. Underliggende 192-raders database ikke innhentet.','publicationVerifiedAt':tr['url']})
