'use client';
import {useEffect,useState,useMemo,type ComponentType} from 'react';
import {ArrowUpRight,Search,Layers,LocateFixed,X,ChevronRight,Database,ExternalLink,Leaf,ArrowLeft,Download,Info} from 'lucide-react';
import {BASE,type Atlas,type Row,type Topic,topics,topicFields,filterProjects,operator,statusGroup,sourceKeys,safeUrl,confidence,details,claimLabel,kindLabels} from '@/lib/model';
type MapProps={projects:Row[];selected:string;onSelect:(id:string)=>void;nature:boolean;reset:number};
const sections:Record<string,string>={baseline:'Naturverdier før inngrep',change:'Endringer og inngrep',consequence:'Vurderte konsekvenser',knowledge_gap:'Kunnskapshull',water_and_land_metrics:'Vann og følgeinngrep'};
function SourceList({ids,data}:{ids:string[];data:Atlas}){return <ul className="sources">{ids.map(id=>{const s=data.sources.find(s=>s.source_key===id);return <li key={id}>{s?<><a href={safeUrl(s.url)} target="_blank" rel="noreferrer">{String(s.title)} <ArrowUpRight size={12}/></a><span>{s.publisher} · Publisert {s.published_at||s.document_date||'dato ikke oppgitt'} · Lest {s.accessed_at||'dato ikke oppgitt'}</span>{s.locator&&<span>{s.locator}</span>}</>:<>Kilde mangler: {id}</>}</li>;})}</ul>;}
function Claim({row,data}:{row:Row;data:Atlas}){const d=details(row);return <article className="claim"><div className="claim-top"><span>{kindLabels[String(row.value_kind)]||String(row.value_kind||row.topic).replaceAll('_',' ')}</span><span className="confidence">Konfidens: {confidence(row.confidence)}</span></div><p className={row.numeric_value!==null?'number-value':''}>{row.numeric_value!==null?new Intl.NumberFormat('nb-NO').format(Number(row.numeric_value)):row.statement}{row.unit&&<small> {row.unit==='persons'?'personer':row.unit}</small>}</p><p className="meta">{claimLabel(row)} · Periode: {row.reference_period||'ikke oppgitt'}</p><p className="reason">{String(d.reason||row.assessment||'Usikkerhet ikke nærmere dokumentert.')}</p>{d.publishAsFact===false&&<p className="caution">Skal ikke leses som en uavhengig bekreftet opplysning.</p>}<details><summary>Kilder og dokumentasjon <ExternalLink size={12}/></summary><SourceList ids={sourceKeys(row.source_keys)} data={data}/>{row.source_locator&&<p className="meta">Kildested: {row.source_locator}</p>}</details></article>;}
function Nature({project,data}:{project:Row;data:Atlas}){const rows=data.nature.filter(r=>r.project_id===project.project_id);return <><div className="note"><Leaf size={18}/><p>Kartlaget viser registrert vern. Nærhet eller overlapp er ikke i seg selv dokumentasjon på naturtap. Fravær av vern betyr ikke lav naturverdi.</p></div>{!rows.length&&<div className="empty-card"><h3>Naturkort ikke ferdigstilt</h3><p>Prosjektet mangler en samlet gjennomgang av naturutredninger, førtilstand og dokumenterte inngrep.</p></div>}{Object.entries(sections).map(([section,title])=>{const items=rows.filter(r=>r.section===section);if(!items.length)return null;return <section key={section} className="nature-section"><h3>{title}</h3>{section==='water_and_land_metrics'?<><p className="reason">Målte vannmengder og faktisk naturtap er ikke dokumentert i dette utvalget.</p><p className="meta">{items[0].statement}</p><details><summary>Kilder og avgrensning</summary><SourceList ids={sourceKeys(items[0].source_keys)} data={data}/><p>{items[0].limitations}</p></details></>:items.map(r=><article className="claim" key={String(r.id)}><p>{r.statement}</p><p className="meta">Periode: {r.reference_period||'ikke oppgitt'} · Konfidens: {confidence(r.confidence)}</p><p className="reason">{r.limitations}</p><details><summary>Kilder og dokumentasjon</summary><SourceList ids={sourceKeys(r.source_keys)} data={data}/><p className="meta">{r.source_locator}</p></details></article>)}</section>;})}</>;}
export default function AtlasView(){
 const [data,setData]=useState<Atlas|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[Map,setMap]=useState<ComponentType<MapProps>|null>(null);
 const [q,setQ]=useState(''),[municipality,setMunicipality]=useState(''),[op,setOp]=useState(''),[status,setStatus]=useState(''),[selected,setSelected]=useState(''),[tab,setTab]=useState<Topic>('Natur'),[nature,setNature]=useState(false),[reset,setReset]=useState(0),[about,setAbout]=useState(false),[audit,setAudit]=useState(false),[mobile,setMobile]=useState('liste'),[urlReady,setUrlReady]=useState(false);
 useEffect(()=>{import('./map').then(m=>setMap(()=>m.default)).catch(()=>{});const p=new URLSearchParams(location.search);setQ(p.get('q')||'');setMunicipality(p.get('kommune')||'');setOp(p.get('operator')||'');setStatus(p.get('status')||'');setSelected(p.get('prosjekt')||'');setUrlReady(true);},[]);
 useEffect(()=>{const controller=new AbortController();setError('');fetch(BASE+'/api/atlas',{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(setData).catch(e=>{if(e.name!=='AbortError')setError('Vi kunne ikke hente prosjektdata fra ODP. Ingen tomme verdier tolkes som null påvirkning.');});return()=>controller.abort();},[retry]);
 useEffect(()=>{if(!urlReady)return;const p=new URLSearchParams();for(const [key,val] of [['q',q],['kommune',municipality],['operator',op],['status',status],['prosjekt',selected]])if(val)p.set(key,val);history.replaceState(null,'',location.pathname+(p.size?'?'+p.toString():''));},[q,municipality,op,status,selected,urlReady]);
 useEffect(()=>{if(!about)return;const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')setAbout(false);if(e.key==='Tab'){const elements=Array.from(document.querySelectorAll<HTMLElement>('.about button:not(:disabled), .about a[href]'));const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler);},[about]);
 const projects=useMemo(()=>filterProjects(data?.projects||[],q,municipality,op,status),[data,q,municipality,op,status]);
 const current=data?.projects.find(p=>p.project_id===selected);
 const choose=(id:string)=>{setSelected(id);setAudit(false);};
 const clear=()=>{setQ('');setMunicipality('');setOp('');setStatus('');};
 const download=()=>{if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify({...data,purpose:'KI-drevet demo. Ikke beslutningsstøtte.'},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`datasentre-${data.release}.json`;a.click();URL.revokeObjectURL(url);};
 return <main className="atlas"><a className="skip" href="#projects">Gå til prosjektlisten</a><header className="header"><a href="https://www.oceandatajo.com/labs" className="brand"><span className="brand-symbol">≋</span> OCEAN DATA JO <span className="labs">/ LABS</span></a><div className="header-links"><button onClick={()=>{setAudit(!audit);setSelected('');}}>Påstandskontroll</button><button onClick={()=>setAbout(!about)}>Om dataene <Info size={15}/></button><a href="https://github.com/joevstaas/datasenter-analyse-norge" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={16}/></a></div></header>
 <div className="demo"><span className="demo-tag">FORSKNINGSDEMO</span><p>KI-drevet datainnhenting · Kun demonstrasjon, ikke beslutningsstøtte.</p><span className="release">Dataversjon 05.10.2026</span></div>
 <section className="workspace"><aside className={'sidebar '+(mobile==='kart'?'mobile-hidden':'')}><div className="intro"><p className="eyebrow">DIGITAL INFRASTRUKTUR / NORGE</p><h1>Datasentre.<br/><em>Et landskap i endring.</em></h1><p className="lead">Utforsk prosjektene, naturen og kunnskapen vi har — og det vi fortsatt ikke vet.</p><div className="stats"><div><strong>{data?.projects.length??'–'}</strong><span>prosjekter i utvalget</span></div><div><strong>5</strong><span>perspektiver</span></div></div></div>
 <div className="filters"><label className="search"><Search size={17}/><input aria-label="Søk etter prosjekt eller kommune" placeholder="Søk prosjekt eller kommune" value={q} onChange={e=>setQ(e.target.value)}/>{q&&<button aria-label="Tøm søk" onClick={()=>setQ('')}><X size={15}/></button>}</label><div className="selects"><select aria-label="Kommune" value={municipality} onChange={e=>setMunicipality(e.target.value)}><option value="">Alle kommuner</option>{Array.from(new Set(data?.projects.map(p=>String(p.municipality)))).sort().map(v=><option key={v}>{v}</option>)}</select><select aria-label="Operatør" value={op} onChange={e=>setOp(e.target.value)}><option value="">Alle operatører</option>{Array.from(new Set(data?.projects.map(operator))).sort().map(v=><option key={v}>{v}</option>)}</select></div><select aria-label="Rapportert prosjektstatus" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Alle rapporterte statuser</option>{Array.from(new Set(data?.projects.map(statusGroup))).sort().map(v=><option key={v}>{v}</option>)}</select></div>
 <div className="list-heading"><span>{projects.length} PROSJEKTER</span>{(q||municipality||op||status)&&<button onClick={clear}>Nullstill filtre</button>}</div><div id="projects" className="project-list" tabIndex={-1}>{error?<div className="empty-card" role="alert"><p>{error}</p><button onClick={()=>setRetry(retry+1)}>Prøv igjen</button></div>:!data?<p className="loading">Henter kildebelagte data fra ODP …</p>:!projects.length?<div className="empty-card"><h3>Ingen prosjekter matcher</h3><p>Prøv et annet søk eller nullstill filtrene.</p><button onClick={clear}>Vis alle prosjekter</button></div>:projects.map((p,i)=><button key={String(p.id)} className={'project-row '+(p.project_id===selected?'active':'')} onClick={()=>choose(String(p.project_id))}><span className="project-no">{String(i+1).padStart(2,'0')}</span><span><small>{String(p.municipality).toUpperCase()} · {operator(p)}</small><strong>{String(p.name).replace('Green Mountain ','').replace('Google / WS Computing – ','').replace('Bulk Infrastructure – ','')}</strong><span className="row-status">{statusGroup(p)}</span></span><ChevronRight size={17}/></button>)}</div><footer className="list-footer"><Database size={14}/><span>{data?'ODP · kildebelagt utvalg':'Ocean Data Platform'}<br/>Ikke en nasjonal totaloversikt</span><button aria-label="Last ned demoens datagrunnlag" onClick={download} disabled={!data}><Download size={17}/></button></footer></aside>
 <section className={'map-area '+(mobile==='liste'?'mobile-map-hidden':'')} aria-label="Kart"><div className="map-toolbar"><button className={nature?'on':''} aria-pressed={nature} onClick={()=>setNature(!nature)}><Layers size={17}/>{nature?'Verneområder på':'Vis verneområder'}</button><button aria-label="Vis hele prosjektutvalget" onClick={()=>{setSelected('');setReset(reset+1);}}><LocateFixed size={18}/></button></div>{Map?<Map projects={projects} selected={selected} onSelect={choose} nature={nature} reset={reset}/>:<div className="map-loading">Laster kart …</div>}<div className="context-label"><span>NORGE</span><small>Infrastruktur møter landskap</small></div>{nature&&<div className="nature-key"><Leaf size={15}/><div><strong>Registrerte verneområder</strong><a href="https://kart.miljodirektoratet.no/arcgis/rest/services/vern/MapServer" target="_blank" rel="noreferrer">Miljødirektoratet / Naturbase ↗</a><small>Levende karttjeneste · hentet ved visning {new Date().toLocaleDateString('nb-NO')} · kan være bufret inntil ett døgn</small></div></div>}</section>
 {current&&data&&<aside className="detail-panel" aria-label="Prosjektdetaljer"><div className="detail-heading"><p className="eyebrow">{String(current.municipality).toUpperCase()} / {operator(current)}</p><button aria-label="Lukk prosjektdetaljer" onClick={()=>setSelected('')}><X size={20}/></button><h2>{current.name}</h2><p className="status-note">{current.status}</p><span className="pill">{current.status_verified?'Driftsstatus kontrollert':'Driftsstatus ikke verifisert som aktuell'}</span></div><nav className="tabs" aria-label="Prosjektperspektiver">{topics.map(t=><button aria-pressed={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</nav><div className="detail-body"><p className="detail-demo">KI-drevet demo · Ikke beslutningsstøtte</p>{tab==='Natur'&&<Nature project={current} data={data}/>} {data.claims.filter(r=>r.project_id===current.project_id&&topicFields[tab].includes(String(r.topic))).map(r=><Claim key={String(r.id)} row={r} data={data}/>)}{tab==='Kraft'&&<div className="empty-card"><h3>Målt årlig kraftbruk: ikke dokumentert</h3><p>MW beskriver effekt eller kapasitet, ikke årlig energibruk. Tallene summeres ikke.</p></div>}{tab==='Areal'&&<div className="empty-card"><h3>Faktisk arealbeslag: ikke dokumentert</h3><p>Campus, tomt og planområde er ulike størrelser. Planpolygoner vises først etter kontroll av koordinatsystem og avgrensning.</p></div>}<details className="location"><summary>Kartpunkt og stedfesting</summary><p>{current.location_uncertainty}</p><p className="meta">WGS84: {Number(current.latitude).toFixed(6)}, {Number(current.longitude).toFixed(6)} · Adressepunkt</p><SourceList ids={sourceKeys(current.location_sources)} data={data}/></details><section className="gaps"><h3>Dette vet vi ikke ennå</h3><p>{current.knowledge_gaps}</p></section><button className="back-button" onClick={()=>setSelected('')}><ArrowLeft size={15}/>Tilbake til oversikten</button></div></aside>}
 {audit&&data&&<aside className="detail-panel audit" aria-label="Påstandskontroll"><div className="detail-heading"><button aria-label="Lukk påstandskontroll" onClick={()=>setAudit(false)}><X size={20}/></button><p className="eyebrow">KILDER / ETTERPRØVING</p><h2>Påstandskontroll</h2><p className="status-note">Publisert rapport, offentlig omtale og kontrollspørsmål holdes adskilt. Dette er forskningsnotater, ikke en endelig faktasjekk.</p></div><div className="detail-body">{data.claims.filter(r=>r.project_id===null).map(r=>{const d=details(r);return <article className="claim" key={String(r.id)}><p>{r.statement}</p><p className="reason">{String(d.reason||r.assessment)}</p>{d.gaps instanceof Array&&<p className="caution">Gjenstår: {d.gaps.join(' ')}</p>}<details><summary>Kilder og full kontrollpost</summary><SourceList ids={sourceKeys(r.source_keys)} data={data}/><pre>{JSON.stringify(d,null,2)}</pre></details></article>;})}</div></aside>}
 </section><div className="mobile-switch"><button aria-pressed={mobile==='liste'} onClick={()=>setMobile('liste')}>Prosjektliste</button><button aria-pressed={mobile==='kart'} onClick={()=>setMobile('kart')}>Kart</button></div>
 {about&&<div className="modal-backdrop" onClick={()=>setAbout(false)}><section role="dialog" aria-modal="true" aria-label="Om dataene" className="about" onClick={e=>e.stopPropagation()}><button autoFocus aria-label="Lukk om dataene" onClick={()=>setAbout(false)}><X/></button><p className="eyebrow">METODE OG BEGRENSNINGER</p><h2>Et kart over det vi vet.<br/>Og hullene mellom.</h2><p>Åtte utvalgte prosjekter gir et første innblikk i datasenterindustrien. Utvalget er ikke representativt og kan ikke brukes til nasjonale estimater.</p><p>Opplysningene er samlet inn med KI og har begrenset kvalitetskontroll. Kilder kan være operatørutsagn, prognoser eller historiske dokumenter. Les dato, definisjon og forbehold ved hver opplysning.</p><p>Konfidens beskriver kildebelegget, ikke en statistisk sannsynlighet. Ukjent betyr ikke null. Kartpunkter dokumenterer adresser; de angir ikke hvor mye natur som er bygget ned.</p><p className="note">Kun demonstrasjon. Ikke beslutningsstøtte.</p><p className="meta">{data?.origin} · Utgivelse {data?.release}<br/>Hentet {data?new Date(data.fetchedAt).toLocaleString('nb-NO'):'ikke hentet'}</p><button className="download" onClick={download}><Download size={16}/>Last ned datagrunnlaget</button></section></div>}
 </main>;
}
