'use client';
import {useEffect,useState} from 'react';
import {BASE} from '@/lib/model';
import {natureLayers,natureLayerKeys,natureService,type NatureLayer} from '@/lib/nature-layers';
export function NatureControls({enabled,onChange,zoom}:{enabled:NatureLayer[];onChange:(v:NatureLayer[])=>void;zoom:number}){
 const [open,setOpen]=useState(false);
 return <div className="nature-controls"><button className="nature-menu-button" aria-expanded={open} onClick={()=>setOpen(!open)}>Natur rundt prosjektet {enabled.length>0&&`(${enabled.length})`}</button>{open&&<div className="nature-menu"><p>Naturverdier og kunnskapshull</p><small>Nærhet er ikke dokumentert påvirkning. Klikk i en kartflate for fakta. Adressepunktene er ikke anleggsgrenser.</small>{natureLayerKeys.map(key=>{const l=natureLayers[key],active=enabled.includes(key);return <section key={key}><label><input type="checkbox" checked={active} onChange={()=>onChange(active?enabled.filter(k=>k!==key):[...enabled,key])}/>{l.name}</label><small>{l.description}</small>{active&&<>{zoom<l.minzoom&&<p className="caution">Zoom inn for å se dette laget (zoom 8 eller nærmere).</p>}<Legend layer={key}/><small>{l.limitation}</small><a href={natureService(key)+'/'+l.layer} target="_blank" rel="noreferrer">Kilde og metadata ↗</a></>}</section>;})}<small>Miljødirektoratet / Naturbase · tjenester kontrollert 05.10.2026. Hentes ved visning; kan være bufret inntil ett døgn. Kartleggingsår finnes ved klikk, der oppgitt.</small></div>}</div>;
}
function Legend({layer}:{layer:NatureLayer}){
 const [items,setItems]=useState<{label:string;imageData:string;contentType:string}[]|null>(null),[error,setError]=useState(false);
 useEffect(()=>{const c=new AbortController();fetch(`${BASE}/api/natur?layer=${layer}&mode=legend`,{signal:c.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>setItems(d.legend)).catch(e=>{if(e.name!=='AbortError')setError(true);});return()=>c.abort();},[layer]);
 return <div className="nature-legend">{error?'Tegnforklaring kunne ikke lastes.':!items?'Henter tegnforklaring …':items.map((item,i)=><span key={i}><img alt="" src={`data:image/png;base64,${item.imageData}`} width={24} height={24}/>{item.label||natureLayers[layer].name}</span>)}</div>;
}
export type NatureResult={layer:NatureLayer;features:Record<string,unknown>[];truncated?:boolean;source?:string;retrievedAt?:string;error?:boolean};
export function NatureFacts({results,loading,onClose}:{results:NatureResult[];loading:boolean;onClose:()=>void}){
 return <aside className="nature-facts" aria-label="Naturfakta på kartpunkt"><button aria-label="Lukk naturfakta" onClick={onClose}>×</button><h3>Natur på kartpunktet</h3><p>Treff i aktive lag ved klikkpunktet. Dette dokumenterer ikke påvirkning fra datasenteret.</p>{loading?<p role="status">Henter naturfakta …</p>:results.map(r=><section key={r.layer}><h4>{natureLayers[r.layer].name}</h4>{r.error?<p role="alert">Oppslag feilet. Ingen konklusjon om naturverdier.</p>:!r.features.length?<p>Ingen registrert flate på klikkpunktet i dette laget. Det betyr ikke fravær av naturverdier.</p>:r.features.map((f,i)=><dl key={i}>{Object.entries(f).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v===null||v===''?'Ikke oppgitt':/faktaark|rapport|instruks/i.test(k)&&/^https:\/\//.test(String(v))?<a href={String(v)} target="_blank" rel="noreferrer">Åpne kildedokument ↗</a>:/dato/i.test(k)&&typeof v==='number'?new Date(v).toLocaleDateString('nb-NO'):String(v)}</dd></div>)}</dl>)}{r.truncated&&<p>Flere enn ti treff. Listen er avkortet.</p>}{r.source&&<a href={r.source} target="_blank" rel="noreferrer">Miljødirektoratet / Naturbase ↗</a>}{r.retrievedAt&&<small>Hentet {new Date(r.retrievedAt).toLocaleString('nb-NO')} · kan være bufret inntil ett døgn.</small>}</section>)}</aside>;
}
